apiVersion: v1
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval:     25s
      evaluation_interval: 15s

      external_labels:
          monitor: 'Alertmanager'

    scrape_configs:

      - job_name: 'gameportal'
        static_configs:
          - targets: ['game-portal:8000']
      - job_name: 'stats_tracker'
        static_configs:
          - targets: ['stats-tracker:5001']
      - job_name: 'matchmaker'
        static_configs:
          - targets: ['matchmaker-worker:5051']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
