repos:
  - repo: "local"
    hooks:
      - id: "game-rps-lint-test"
        name: "Run RPS linters and tests"
        entry: run-project-checks.sh
        language: "script"
        description: "This will trigger a script that runs linters on game server and client, and run server tests"